# Generated by Django 4.1.4 on 2022-12-16 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='user',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='user',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='experiences',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='user',
        ),
        migrations.DeleteModel(
            name='AchievmentsDocuments',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='achievementdocuments',
            name='achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='start.achievements'),
        ),
    ]
