# Generated by Django 4.1.4 on 2022-12-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_achievementdocuments_remove_achievements_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
