# Generated by Django 4.1.4 on 2022-12-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0004_projects_project_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
