# Generated by Django 4.1.4 on 2022-12-17 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0005_projects_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='achievementdocuments',
            name='achievement',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
        migrations.DeleteModel(
            name='AchievementDocuments',
        ),
    ]
