# Generated by Django 4.1.4 on 2022-12-17 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0006_messages_remove_achievementdocuments_achievement_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievements',
            new_name='Achievement',
        ),
        migrations.RenameModel(
            old_name='Experiences',
            new_name='Experience',
        ),
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
