# Generated by Django 4.1.4 on 2022-12-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0008_remove_education_is_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
